- name: role_load - Load jenkins projects
  include_vars: jenkins_projects.yml
  tags:
    - always

# - name: role_load - Build container projects
#   shell: "ssh {{ console_user }}@{{ groups['console'][0] }} -i {{ ansible_ssh_private_key_file }} -p 8022 -o StrictHostKeyChecking=no build {{ item.name }}"
#   with_items:
#      - "{{ jenkins_demo_projects }}"
#   delegate_to: localhost
#   register: result
#   retries: 5
#   delay: 30
#   when: (item.build) and item.group == "containers"
#   until: result is succeeded



- name: role_load - Build Jenkins wrapper project
  shell: "ssh {{ console_user }}@{{ groups['console'][0] }} -i {{ ansible_ssh_private_key_file }} -p 8022 -o StrictHostKeyChecking=no build Demo-Build-Wrapper"
  delegate_to: localhost
  register: result
  retries: 5
  delay: 10
  until: result is succeeded

# - name: role_load - Deploy demo projects
#   shell: "ssh {{ console_user }}@{{ groups['console'][0] }} -i {{ ansible_ssh_private_key_file }} -p 8022 -o StrictHostKeyChecking=no build {{ item.name }}"
#   delegate_to: "localhost"
#   with_items:
#     - "{{ jenkins_demo_projects }}"
#   register: result
#   retries: 5
#   delay: 10
#   until: result is succeeded
#   when: (item.build) and item.group == "demo"

# - name: role_load - Deploy RASP projects
#   shell: "ssh {{ console_user }}@{{ groups['console'][0] }} -i {{ ansible_ssh_private_key_file }} -p 8022 -o StrictHostKeyChecking=no build {{ item.name }}"
#   delegate_to: "localhost"
#   with_items:
#     - "{{ jenkins_demo_projects }}"
#   register: result
#   retries: 5
#   delay: 10
#   until: result is succeeded
#   when: (item.build) and item.group == "rasp"

# - name: role_load - Build ops projects
#   shell: "ssh {{ console_user }}@{{ groups['console'][0] }} -i {{ ansible_ssh_private_key_file }} -p 8022 -o StrictHostKeyChecking=no build {{ item.name }}"
#   delegate_to: "localhost"
#   with_items:
#     - "{{ jenkins_demo_projects }}"
#   register: result
#   retries: 5
#   delay: 10
#   until: result is succeeded
#   when: (item.build) and item.group == "ops"

# - name: role_load - Run compromises
#   shell: "ssh {{ console_user }}@{{ groups['console'][0] }} -i {{ ansible_ssh_private_key_file }} -p 8022 -o StrictHostKeyChecking=no build {{ item.name }}"
#   delegate_to: "localhost"
#   with_items:
#     - "{{ jenkins_demo_projects }}"
#   register: result
#   retries: 5
#   delay: 10
#   until: result is succeeded
#   when: (item.build) and item.group == "compromise"
