- name: Add custom malware (18.11)
  uri:
    url: "{{ twistlock_console }}/api/v1/feeds/malware"
    method: PUT
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    body: '{"feed":[{"md5":"b927cd908b58e703ab86f484b44a3791","name":"evil-malware-demo","modified":0,"index":0}]}'
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    status_code: 200, 400
  when: twistlock_version.split('.')[0] == "18"

- name: Add custom malware (19.03+)
  uri:
    url: "{{ twistlock_console }}/api/v1/feeds/custom/malware"
    method: PUT
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    body: '{"feed":[{"md5":"b927cd908b58e703ab86f484b44a3791","name":"evil-malware-demo","modified":0,"index":0}]}'
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    status_code: 200, 400
  when: twistlock_version.split('.')[0] != "18"

- name: Wget bad-evil
  command: "docker run busybox wget https://cdn.twistlock.com/john/evil"
