- name: Get Selenium modules
  pip:
    name: selenium, docker
  with_items:
    - selenium
    - docker


- name: Start Selenium stand-alone server
  docker_container:
    name: selenium
    image: selenium/standalone-chrome-debug
    volumes:
      - "/dev/shm:/dev/shm"
      - "/opt/selenium-screenshots:/opt/selenium-screenshots"
    ports:
      - "4444:4444"
      - "5900:5900"

- name: Wait for Selenium on '{{ target_host }}'
  uri:
    url: "http://localhost:4444/"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1

    