- name: Set k8s addr
  set_fact: sockshop_addr="https://sockshop-{{ groups['console'][0]  }}/"

- name: Get Sock Shop containers
  uri:
    url: "{{ twistlock_console }}/api/v1/containers?search=sock-shop"
    method: GET
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
  register: sockshop_images
  retries: 5
  delay: 10
  until: sockshop_images.total_count > 0

- name: Start learning for Sock Shop
  uri:
    url: "{{ twistlock_console }}/api/v1/profiles/container/{{ item.info.profileID }}/learn"
    method: POST
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    body: "{'imageID':'{{ item.info.profileID }}', 'state':'manualRelearning'}"
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    status_code: 200, 400
  with_items: "{{ sockshop_images.json }}"

- name: Create /opt/code
  file: path=/opt/code state=directory

- name: Copy SockShop.py
  copy:
    src: SockShop.py
    dest: /opt/code/SockShop.py
    mode: 0744

- name: Start Selenium
  docker_container:
    name: selenium
    image: selenium/standalone-chrome-debug
    state: started


- name: Execute SockShop.py
  command: "python /opt/code/SockShop.py"
  environment:
    test_url: "{{ sockshop_addr }}"
  register: sockshop_out

- name: SockShop.py output
  debug: var=sockshop_out

- name: Run weaveworks load test
  shell: "docker run --net=host weaveworksdemos/load-test -h {{ sockshop_addr | urlsplit('netloc') }} -r 100 -c 2"


# Allowing learning to continue to reduce false positive audits on Sockshop components
# - name: Stop learning for Sock Shop
#  uri:
#    url: "{{ twistlock_console }}/api/v1/profiles/container/{{ item.info.profileID }}/learn"
#    method: POST
#    user: "{{ console_user }}"
#    password: "{{ console_password }}"
#    body: "{'imageID':'{{ item.info.profileID }}', 'state':'manualActive'}"
#    force_basic_auth: yes
#    body_format: json
#    validate_certs: no
#    status_code: 200,400
#  with_items: "{{ sockshop_images.json }}"
