- name: Create harbor secret certs
  shell: "kubectl get secret console-cert -n ingress-nginx -o yaml | grep tls.crt | cut -f2 -d ':'|awk '{$1=$1};1'|base64 --decode|awk 'split_after==1{n++;split_after=0} /-----END CERTIFICATE-----/ {split_after=1} {print > \"tls\" n \".crt\"}' && mv tls1.crt ca.crt"
  delegate_to: "{{ groups['k8s-master'][0] }}"
  
- name: Create harbor secret key
  shell: "kubectl get secret console-cert -n ingress-nginx -o yaml | grep tls.key | cut -f2 -d ':'|awk '{$1=$1};1'|base64 --decode > tls.key"
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Create cert folder
  shell: "mkdir -p /root/cert"
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Copy tls.crt to root
  shell: "cp tls.crt /root/cert/tls.crt"
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Copy tls.key to root
  shell: "cp tls.key /root/cert/tls.key"
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Create docker folder
  shell: "mkdir -p /etc/docker/certs.d/harbor-{{ groups['k8s-master'][0] }}"
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Copy ca.crt to docker
  shell: "cp ca.crt /etc/docker/certs.d/harbor-{{ groups['k8s-master'][0] }}/ca.crt"
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Copy tls.cert to docker tls.cert
  shell: "cp tls.crt /etc/docker/certs.d/harbor-{{ groups['k8s-master'][0] }}/tls.cert"
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Copy tls.key to docker
  shell: "cp tls.key /etc/docker/certs.d/harbor-{{ groups['k8s-master'][0] }}/tls.key"
  delegate_to: "{{ groups['k8s-master'][0] }}"
