- import_tasks: users.yml

# - set_fact:
#     enable_openldap:  false
#   tags:
#     - openldap

# Must create collections before groups for assigned collections
- import_tasks: collections.yml
  tags:
    - collections

- debug: var=enable_openldap

- import_tasks: openldap.yml
  when: enable_openldap
  tags:
    - openldap

- import_tasks: set_san.yml

- stat: path=/tmp/twistlock_console.pem
  register: cert_file

- import_tasks: install_tls_cert.yml
  when: cert_file.stat.exists == true

# custom rules in place for other rules
- import_tasks: custom-rules.yml



- import_tasks: registry.yml
  when: use

# rules before Jenkins so that serverless rule is there
- import_tasks: rules.yml

- import_tasks: k8s-audit.yml
# - import_tasks: jira.yml
# not ready for use



- import_tasks: gogs.yml # setup git before Jenkins

- import_tasks: jenkins.yml


- import_tasks: splunk.yml
  when:
    - not twistlock_console_k8s
    - enable_splunk
- import_tasks: splunk-k8s.yml
  when:
    - twistlock_console_k8s
    - enable_splunk

- import_tasks: splunk-config.yml
  when:
    - enable_splunk


- import_tasks: sumo.yml
  when:
    - not (twistlock_console_k8s)
    - enable_sumo
- import_tasks: sumo-k8s.yml
  when:
    - twistlock_console_k8s
    - enable_sumo

- import_tasks: vault.yml

- import_tasks: portal.yml

  when:
    - twistlock_console_k8s


- import_tasks: defender.yml

- import_tasks: windows_intel_stream.yaml
  tags: windows_intel_stream

# This restart is important even though it seems meaningless
# Without it, iptables ends up h0rked
# and splunk & vault fail to start
# Don't remove it unless you figure out the iptables weirdness
# (ps -fe | grep iptables --> this will show you what I'm talking about
# next time you break it.)

# Actually, forget this restart.  It might have been breaking more than it fixed.

# - import_tasks: restart.yml

# Instead, we're going to delete the daemonSet and recreate it.
# The reboot appeared to cause a scenario where Defender started
# before Console, resulting in a failure to connect to the WSS

- name: Recreate the Defender DS for good measure
  shell: 'kubectl delete -f /opt/defender-ds.yaml && kubectl create -f /opt/defender-ds.yaml'

- import_tasks: jenkins_builds.yml

- import_tasks: scan.yml

- import_tasks: mail.yml

- import_tasks: harbor.yml

- import_tasks: kubeconfig.yml

- import_tasks: cloud-platforms.yml
