- name: restart host
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes
  delegate_to: "{{ item }}"
  with_items: 
  - "{{ groups['k8s-nodes'] }}"
  - "{{ groups['k8s-master'] }}"

- name: Wait for shutdown
  pause: seconds=15

- name: Capture hostname
  debug: var=ansible_host
  register: reboot_host

- name: wait for host
  wait_for:
    delay: 1
    host: "{{ reboot_host.ansible_host }}"
    port: 22
    state: started
    timeout: 360
  delegate_to: localhost

- name: we need to wait for it all to start up...
  uri:
    url: "{{ twistlock_console }}/api/v1/_ping"
    status_code: 200
    validate_certs: false
  register: result
  until: result is succeeded
  retries: 30
  delay: 10 
  delegate_to: localhost

