# Changing the System Scan settings to disable the scan only running Images.
- name: Change System Scan settings
  uri:
    url: "{{ twistlock_console }}/api/v1/settings/scan"
    body: '{"scanRunningImages":false,"imagesScanPeriodMs":86400000,"containersScanPeriodMs":86400000,"systemScanPeriodMs":86400000,"registryScanPeriodMs":86400000,"pcfDropletsScanPeriodMs":86400000,"serverlessScanPeriodMs":86400000,"cloudPlatformsScanPeriodMs":86400000,"extractArchive":false,"showNegligibleVulnerabilities":false}'
    method: POST
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    status_code: 200
