
  - copy:
      src: /etc/letsencrypt/live/
      dest: files/wildcard_cert
    when: test_run == true
    
  - file: 
      path: "/files/group_vars/"
      state: directory

  - file:
      path: /files/.ssh
      state: directory

  - name: Generate SSH key
    shell: 'ssh-keygen -q -t rsa -f /root/.ssh/temp-gce -C "" -N ""'
    args:
      creates: /files/.ssh/temp-gce
    

  - name: Create GCP JSON
    copy:
      content: "{{ gcp_cred_json }}"
      dest: "/files/twistlock-cto-lab.json"


  - template:
      src: test/.ansible.cfg.j2
      dest: /files/.ansible.cfg

  - template:
      src: test/all.yml.j2
      dest: "/files/group_vars/all.yml"

  - template:
      src: test/inventory.yml.j2
      dest: "/files/inventory.yml"