- name: Get host name
  set_fact: target_host={{ ansible_host }}

- name: Delete instance {{ target_host }}
  gce: 
    instance_names: "{{ lookup('shorthostname', target_host) }}" 
    external_ip: "{{ lookup('shorthostname', target_host) }}"
    machine_type: "{{ machine_type }}"
    image: "{{ imag | default( lookup('build_defaults','image') )  }}"
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id | default( lookup('build_defaults','project_id') ) }}"
    disk_size: "{{ disksize }}"
    zone: "{{ zone | default( lookup('build_defaults','zone') )  }}"
    state: absent
  tags:
  - delete
  delegate_to: localhost
  ignore_errors: true
  register: result
  retries: 2
  delay: 10
  until: result is succeeded


