- command: ping -c1 {{ groups['k8s-master'][0] }}
  delegate_to: localhost
  register: ping_result
  ignore_errors: yes

- name: Get persistent disks
  shell: "kubectl get pv --all-namespaces -o json"
  register: pd_result
  delegate_to: "{{ groups['k8s-master'][0] }}"
  # Ignoring errors here to cover case when these are new hosts.
  # This is very BUGBUG but the worst case is that 
  # persistent disks don't get deleted.
  when: ping_result is success
  ignore_errors: true
  
- meta: clear_host_errors

- debug: var=pd_result

- set_fact:
    gce_pds: "{{ (pd_result.stdout | from_json) }}"
  when: 
    - ping_result is success
    - pd_result is success