- name: Get host name
  set_fact: target_host={{ ansible_host }}

- name: Resume instance {{ target_host }}
  gce: 
    instance_names: "{{ target_host | replace('.', '-') | replace('twistlock.com', '') }}" 
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id | default( lookup('build_defaults','project_id') )  }}"
    state: started   
  delegate_to: localhost


- name: Wait for SSH for instance {{ target_host }}
  wait_for:
    delay: 1
    host: "{{ target_host }}"
    port: 22
    state: started
    timeout: 600
  delegate_to: localhost