- name: Get host name
  set_fact: target_host={{ ansible_host }}
  tags: deploy_windows

- name: Create static IP for {{ target_host }}
  gce_eip:
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id | default( lookup('build_defaults','project_id') )  }}"
    name: "{{ lookup('shorthostname', target_host) }}"
    region: "{{ region | default( lookup('build_defaults','region') ) }}"
    state: present
  register: eip
  delegate_to: localhost
  tags: deploy_windows

- name: Create DNS entry for {{ target_host }}
  gcdns_record:
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id | default( lookup('build_defaults','project_id') ) }}"
    record: "{{ target_host | replace('_', '-')  }}"
    zone: "{{ dns_zone  | default( lookup('build_defaults','dns_zone') )}}"
    type: A
    value: "{{ eip.address }}"
    overwrite: true
    ttl: 60
  delegate_to: localhost
  tags: deploy_windows


- name: Launch instance {{ target_host }}
  gce:
    instance_names: "{{ lookup('shorthostname', target_host) }}" 
    external_ip: "{{ lookup('shorthostname', target_host) }}"
    machine_type: "{{ machine_type }}"
    image: "{{ windowsimage  | default( lookup('build_defaults','windowsimage') )}}"
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    persistent_boot_disk: true
    project_id: "{{ project_id | default( lookup('build_defaults','project_id') ) }}"
    disk_size: "{{ disksize }}"
    zone: "{{ zone  | default( lookup('build_defaults','zone') )}}"
    state: active
    service_account_permissions:
        - storage-full
        - cloud-platform      
  delegate_to: localhost
  tags: deploy_windows

- name: Label our instance
  gce_labels:
    resource_name: "{{ lookup('shorthostname', target_host) }}" 
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id | default( lookup('build_defaults','project_id') ) }}"
    resource_location: "{{ zone | default( lookup('build_defaults','zone') )  }}"
    resource_type: instances
    labels:
      owner: "{{ target_user }}"
  delegate_to: localhost  

# - name: Clear DNS cache on MacOS
#   shell: 'sudo killall -HUP mDNSResponder'
#   become: true
#   delegate_to: localhost
#   ignore_errors: yes
#   tags: deploy_windows

# - name: Remove old Windows host key from known hosts
#   connection: local
#   shell: "ssh-keygen -R {{ inventory_hostname }}"
#   retries: 8
#   delay: 1
#   # concurrency issue with running this for multiple hosts simultaneously.
#   delegate_to: localhost
#   register: result
#   until: result.rc == 0
#   when: user_known_hosts.stat.exists == True

- name: Wait for SSH for instance {{ target_host }}
  wait_for:
    delay: 1
    host: "{{ target_host }}"
    port: 22
    state: started
    timeout: 600
  delegate_to: localhost

- name: Write the new Windows host key to known hosts
  connection: local
  shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"
  retries: 5
  delay: 5
  delegate_to: localhost
  register: result
  until: result.rc == 0

- name: Set proper permissions on ./roles/role_windows/files/twistlock_ansible_2019
  file:
    path: ./roles/role_windows/files/twistlock_ansible_2019
    mode: 0600
  delegate_to: localhost
