- name: Add users if it doesn't exist
  blockinfile:
    dest: group_vars/all.yml
    block: "{{ lookup('template', 'users.j2') }}"
    insertbefore: "target_user"
    marker: "# {mark} ANSIBLE MANAGED BLOCK users"
  when: users is not defined

# https://github.com/twistlock/demo_build/pull/84
- name: Make sure jenkins_demo_projects removed from all.yml -- check README if this fails
  lineinfile: 
    dest: group_vars/all.yml
    regexp: "^jenkins_demo_projects:"
    state: absent
  check_mode: yes
  register: presence
  failed_when: presence.changed
  when: (test_run | default(false))

- name: Ensure that one user is in devops or auditor group for assigned collections -- check README if this fails
  lineinfile: 
    dest: group_vars/all.yml
    regexp: "^(      - auditor|      - devops)"
    state: absent
  check_mode: yes
  register: presence
  failed_when: presence.changed==false
  when: (test_run | default(false))

# - name: Add prebuilt_image if it doesn't exist
#   blockinfile:
#     dest: group_vars/all.yml
#     block: "prebuilt_image: false"
#     insertbefore: "image:"
#     marker: "# {mark} ANSIBLE MANAGED BLOCK prebuilt_image <-- change this to use prebuilt images"
#   when: prebuilt_image is not defined

# - name: Add splunk_token if it doesn't exist
#   blockinfile:
#     dest: group_vars/all.yml
#     block: "splunk_token: \"Anál nathrach, orth' bháis's bethad, do chél dénmha\""
#     insertafter: EOF
#     marker: "# {mark} ANSIBLE MANAGED BLOCK splunk_token"
#   when: splunk_token is not defined

# - name: Add dns_zone if it doesn't exist
#   blockinfile:
#     dest: group_vars/all.yml
#     block: "dns_zone: lab.twistlock.com"
#     insertafter: EOF
#     marker: "# {mark} ANSIBLE MANAGED BLOCK dns_zone"
#   when: dns_zone is not defined

# - name: Add default custom_compliance_benchmarks if they don't exist
#   blockinfile:
#     dest: group_vars/all.yml
#     block: "{{ lookup('template', 'custom_compliance_benchmarks.j2') }}"
#     insertbefore: EOF
#     marker: "# {mark} ANSIBLE MANAGED BLOCK custom_compliance_benchmarks"
#   when: custom_compliance_benchmarks is not defined

# - name: Add Windows image
#   blockinfile:
#     dest: group_vars/all.yml
#     block: 'windowsimage: "https://www.googleapis.com/compute/v1/projects/cto-sandbox/global/images/windows2019-demo-build-v2"'
#     insertbefore: EOF
#     marker: "# {mark} ANSIBLE MANAGED BLOCK windowsimage"
#   when: windowsimage is not defined 

- name: Get timestamp
  stat:
    path: group_vars/all.yml
  register: stat_all
  delegate_to: localhost

- debug: var=ansible_date_time.epoch 

- debug: var=stat_all.stat.ctime

# - fail:
#    msg: "Please restart playbook to refresh group_vars after change."
#  when: (((ansible_date_time.epoch | float) < (stat_all.stat.ctime )) )
