- name: Create creds dir
  file: dest="files/{{ groups['console'][0] }}/creds/" mode=0755 state=directory

- name: Upgrade the pip package
  shell: apk update & apk upgrade pip

- name: Upgrade pip version
  shell: "pip install --upgrade pip"

- name: Install xkcdpass
  pip:
    name: xkcdpass

- name: Generate passwords
  shell: "xkcdpass -n 4 -d . --min 3 --max 5 > files/{{ groups['console'][0] }}/creds/{{ item.username }}"
  when: item.password == "..generate.."
  with_items: "{{ users }}"

- name: Write passwords
  shell: "echo '{{ item.password }}' > files/{{ groups['console'][0] }}/creds/{{ item.username }}"
  when: item.password != "..generate.."
  with_items: "{{ users }}"
