- name: Get host name
  set_fact: target_host={{ ansible_host }}

- set_fact: dns_zone="lab.twistlock.com"
  when: dns_zone is not defined

- set_fact: dns_project_id="cto-sandbox"
  when: dns_project_id is not defined

- name: Gather local OS
  setup:
  delegate_to: localhost

- name: Read static IP for {{ target_host }}
  gce_eip:
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id | default( lookup('build_defaults','project_id') )  }}"
    name: "{{ target_host | replace('_', '-') | replace('.', '-') }}"
    region: "{{ region | default( lookup('build_defaults','region') )  }}"
    state: present
  register: eip
  delegate_to: localhost

- debug: var=eip.address

- set_fact: temp=""

- name: Get the default SSH key
  command: cat {{ ansible_ssh_private_key_file }}.pub
  register: ssh_key
  delegate_to: localhost

- name: Generate the SSH key JSON
  set_fact: temp='{"sshKeys":"{{ target_user }}:{{ ssh_key.stdout }}"}'
  delegate_to: localhost

- name: Clear DNS cache on MacOS
  shell: 'sudo killall -HUP mDNSResponder'
  become: true
  delegate_to: localhost
  ignore_errors: yes
  when: ansible_distribution == 'MacOSX'

- name: Wait for SSH for instance {{ target_host }}
  wait_for:
    delay: 1
    host: "{{ target_host }}"
    port: 22
    state: started
    timeout: 600
  delegate_to: localhost
