- name: Concatenate certs
  command: "sed w/tmp/twistlock_console.pem /etc/letsencrypt/live/'{{ domain_root }}'/cert.pem /etc/letsencrypt/live/'{{ domain_root }}'/privkey.pem"
  args:
    warn: false # Ansible would prefer we don't use sed but it's significantly more convenient here.

- name: Build cert json
  command: cat /tmp/twistlock_console.pem 
  register: console_cert

- name: Prep domain.key for registry
  command: cp /etc/letsencrypt/live/{{ domain_root }}/privkey.pem /etc/letsencrypt/live/{{ domain_root }}/domain.key

- name: Prep domain.crt for registry
  command: sed w/etc/letsencrypt/live/{{ domain_root }}/domain.crt /etc/letsencrypt/live/{{ domain_root }}/cert.pem /etc/letsencrypt/live/{{ domain_root }}/chain.pem
  args:
    warn: false # Ansible would prefer we don't use sed but it's significantly more convenient here.
    
- name: Set permissions
  file:
    path: "{{ item }}"
    mode: 0777
  with_items:
    - /etc/letsencrypt/live/{{ domain_root }}/domain.crt
    - /etc/letsencrypt/live/{{ domain_root }}/domain.key
