- name: copy auth json
  copy:
    src: "{{ credentials_file_dns }}"
    dest: "/opt/{{ credentials_file_dns | basename }}"

- name: Generate cert
  command: "docker run -i --rm --name certbot -v /opt:/tmp -v /etc/letsencrypt:/etc/letsencrypt -v /var/log/letsencrypt:/var/log/letsencrypt certbot/dns-google  certonly --dns-google --server https://acme-v02.api.letsencrypt.org/directory  --non-interactive --email {{ emailaddr }} --dns-google-credentials /tmp/{{ credentials_file_dns | basename }} --agree-tos -d *.{{ domain_root }} "

- name: delete auth json
  file:
    path: "/opt/{{ credentials_file | basename }}"
    state: absent

- name: Create local copy of private key
  fetch:
    src: /etc/letsencrypt/live/{{ domain_root }}/{{ item }}
    dest: files/wildcard_cert/{{ domain_root }}/{{ item }}
    flat: yes
  with_items:
    - privkey.pem
    - cert.pem
    - chain.pem

- name: Make sure we have a local cert dir
  file:
    path: /etc/letsencrypt/live/{{ domain_root }}
    state: directory
  delegate_to: localhost

- name: Copy to /etc/letsencrypt as well
  copy:
    src: files/wildcard_cert/{{ domain_root }}/{{ item }}
    dest: /etc/letsencrypt/live/{{ domain_root }}/{{ item }}
  with_items:
    - privkey.pem
    - cert.pem
    - chain.pem
  delegate_to: localhost
