
- name: Get ingress-nginx YAML
  get_url: 
   url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/1cd17cd12c98563407ad03812aebac46ca4442f2/deploy/mandatory.yaml
   dest: /opt/ingress-nginx.yml

- name: Add hostPort
  lineinfile:
    path: /opt/ingress-nginx.yml
    insertafter: '            containerPort: {{ item }}'
    line: '              hostPort: {{ item }}'
  with_items:
    - 80
    - 443

- name: Add nodeSelector
  lineinfile:
    path: /opt/ingress-nginx.yml
    insertafter: 'timeoutSeconds: 10'
    line: "      nodeSelector:\n        kubernetes.io/hostname: {{ ansible_hostname }}"

- name: Install nginx-ingress
  command: kubectl apply -f /opt/ingress-nginx.yml
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install nginx-ingress service
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/1cd17cd12c98563407ad03812aebac46ca4442f2/deploy/provider/baremetal/service-nodeport.yaml
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

- name: Copy ingress template
  template:
    src: ingress.yml.j2
    dest: /opt/ingress.yml

- name: Apply ingress yml
  command: kubectl apply -f /opt/ingress.yml
