- name: Download longhorn.yaml
  get_url:
    url: https://raw.githubusercontent.com/rancher/longhorn/master/deploy/longhorn.yaml
    dest: /opt/longhorn.yaml

# Using my own longhorn.yaml to get latest

#- name: Copy longhorn.yaml
#  copy:
#    src: files/longhorn.yaml
#
    dest: /opt/longhorn.yaml

- name: Change to NodePort
  lineinfile:
    path: /opt/longhorn.yaml
    regexp: '^  type: LoadBalancer'
    line: '  type: NodePort'

- name: Install longhorn distributed block storage
  command: kubectl apply -f /opt/longhorn.yaml
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

- name: Copy storage class YAML
  copy:
    src: longhorn_storage_class.yml
    dest: /root/longhorn_storage_class.yml

- name: Create storage class
  command: kubectl apply -f /root/longhorn_storage_class.yml
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

- name: Waiting to let storage come up
  pause: minutes=1