- name: Set domain root in secrets
  set_fact: domain_root="{{ groups['console'][0] }}"
  when: domain_root is undefined

- name: Namespace array
  set_fact:
    namespaces:
      - twistlock
      - sock-shop
      - kube-system
      - infra
      - dvwa
      - ingress-nginx
      - docker-registry
      - bookinfo
      - struts-demo
      - monitoring

- name: Create htpasswd file
  command: "htpasswd -b -c /opt/auth admin '{{ new_password }}'"

- name: Add other users to htpasswd
  command: "htpasswd -b /opt/auth {{ item.username }} '{{ lookup('password', 'files/' + groups['console'][0] + '/creds/' + item.username) }}'"
  with_items: "{{ users }}"

- name: Capture existing namespaces
  shell: kubectl get namespaces -o=name | sed 's#^namespaces/##'
  register: active_namespaces
  changed_when: false
  ignore_errors: true

- name: Make sure namespaces exist
  command: "kubectl create namespace {{ item }}"
  ignore_errors: yes
  with_items: "{{ namespaces }}"
  when: item not in active_namespaces.stdout_lines

- name: Add pull secret for artifactory
  command: "kubectl create secret docker-registry demo-build-registry --docker-server=demo-build.{{ artifactory_url | urlsplit('hostname') }} --docker-username={{ artifactory_user }} --docker-password={{ artifactory_password }} --docker-email=cto@twistlock.com -n {{ item }}"
  ignore_errors: yes
  with_items: "{{ namespaces }}"  

- name: Add basic-auth secrets
  command: "kubectl -n {{ item }} create secret generic basic-auth --from-file=/opt/auth"
  ignore_errors: yes
  with_items: "{{ namespaces }}"

- name: Add TLS cert secrets
  command: "kubectl -n {{ item }} create secret tls console-cert --key /etc/letsencrypt/live/{{ domain_root }}/domain.key --cert /etc/letsencrypt/live/{{ domain_root }}/domain.crt"
  ignore_errors: yes
  with_items: "{{ namespaces }}"
