- name: Get storageos helm chart
  git:
    repo: 'https://github.com/storageos/helm-chart.git'
    dest: /opt/storageos

- debug: var=ansible_default_ipv4.address

- name: Install storageos
  command: helm install --name my-release --set cluster.join="http://{{ ansible_default_ipv4.address }}:5705" .
  args:
     chdir: /opt/storageos

- name: Get ClusterIP
  shell: kubectl get svc/storageos --namespace default -o custom-columns=IP:spec.clusterIP --no-headers=true
  register: ClusterIP
  retries: 5
  delay: 30
  until: ClusterIP.rc == 0

- debug: var=ClusterIP

- name: Get API addr
  shell: echo -n "tcp://{{ ClusterIP.stdout }}:5705" | base64
  register: ApiAddress

# - debug: msg=kubectl patch secret/storageos-api --patch "{\"/data\":{\"/apiAddress\": \"{{ ApiAddress }}\"}"

- name: Copy storageos-secret.yml
  template:
    src: storageos-secret.yml.j2
    dest: /opt/storageos-secret.yml

- name: Patch storageos
  command: 'kubectl patch secret/storageos-api --patch "{\"data\":{\"apiAddress\": \"{{ ApiAddress.stdout }}\"}}"'
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install StorageOS CLI
  shell: curl -sSLo storageos https://github.com/storageos/go-cli/releases/download/1.0.0-rc1/storageos_linux_amd64 && chmod +x storageos && sudo mv storageos /usr/local/bin/
  
- lineinfile:
    path: /etc/environment
    line: '{{ item }}'
  with_items:
    - "STORAGEOS_USERNAME=storageos"
    - "STORAGEOS_PASSWORD=storageos"
    - "STORAGEOS_HOST={{ ClusterIP }}"
