- name: Add insecure registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Get host name
  set_fact: target_host={{ ansible_host }}

- name: restart host
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  become: yes

- name: Wait for SSH for instance {{ ansible_host }}
  wait_for:
    delay: 1
    host: "{{ target_host }}"
    port: 22
    state: started
    timeout: 600
  delegate_to: localhost

- name: Waiting an extra 30 seconds to make sure everything is up
  pause: seconds=30
  delegate_to: localhost