- name: "Install Helm"
  shell: curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  args:
    warn: false # set warn=false to prevent warning
  register: result
  retries: 10
  delay: 10
  ignore_errors: true
  until: result is succeeded

- name: Init helm
  command: helm init
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: true

- name: Create tiller service account
  command: kubectl create serviceaccount --namespace kube-system tiller
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: true

- name: Add tiller cluster rule
  command: kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: true

- name: ...and apply it.
  command: kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: true

- name: Wait for ClusterIP for tiller deployment
  shell: kubectl get svc/tiller-deploy --namespace kube-system -o custom-columns=IP:spec.clusterIP --no-headers=true
  retries: 5
  delay: 30
  register: results
  until: results.rc == 0
  ignore_errors: true
