- name: Copy kubeadm conf
  template:
    src: kubeadmconf.yml.j2
    dest: /opt/kubeadmconf.yml
    # This sets necessary features for GCE & StorageOS and a fixed key for adding nodes

- name: create a place for cloud.conf
  file: dest="/etc/kubernetes" owner=root group=root mode=0755 state=directory

- name: create a place for cloud.conf
  file: dest="/etc/kubernetes/pki" owner=root group=root mode=0755 state=directory

- name: Copy cloud.conf
  template:
    src: cloud.conf.j2
    dest: /etc/kubernetes/pki/cloud.conf
    # workaround for https://github.com/kubernetes/kubeadm/issues/484, putting in pki/

- name: Check k8s version
  command: kubeadm version -o yaml
  register: k8s_version



- name: Run the kubeadm init command
  command: kubeadm init --ignore-preflight-errors=all --config=/opt/kubeadmconf.yml 
  register: kubeadmcommand



- name: Apply calico etcd
  command: kubectl apply -f https://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/etcd.yaml
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  retries: 8
  delay: 10
  # For no apparent reason, this returns a 50x result occasionally
  register: result
  until: result.rc == 0
  when: k8s_cni_val == "Calico"

- name: Apply Calico networking
  command: kubectl apply -f https://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/calico.yaml
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  retries: 8
  delay: 10
  # For no apparent reason, this returns a 50x result occasionally
  register: result
  until: result.rc == 0
  when: k8s_cni_val == "Calico"

- name: Apply Flannel networking
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.11.0/Documentation/kube-flannel.yml
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  retries: 8
  delay: 10
  # For no apparent reason, this returns a 50x result occasionally
  register: result
  until: result.rc == 0
  when: k8s_cni_val == "Flannel"

- name: Apply Weave networking
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
  retries: 8
  delay: 10
  # For no apparent reason, this returns a 50x result occasionally
  register: result
  until: result.rc == 0
  when: k8s_cni_val == "Weave"  

- name: Set master to schedulable
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  environment:
      KUBECONFIG: /etc/kubernetes/admin.conf


- name: Create $HOME/.kube
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/root/.kube"
    - "/home/{{ target_user }}/.kube"

- name: Copy admin.conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ item }}"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    remote_src: yes
  with_items:
    - "/root/.kube/config"
    - "/home/{{ target_user }}/.kube/config"

- name: Set permissions
  file:
    path: "/home/{{ target_user }}/.kube"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Create local config copy
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: files/kubeconfig/{{ domain_root }}/config
    flat: yes

- name: Enable autocomplete
  lineinfile:
    path: "{{ item }}"
    line: 'source <(kubectl completion bash)'
    state: present
  with_items:
    - "/home/{{ target_user }}/.bashrc"
    - "/etc/bash.bashrc"







