
- name: Add insecure registry
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  register: result
  retries: 5
  delay: 10
  until: result is succeeded

- name: Add user to Docker group
  user: name={{ ansible_user  }}
        group=docker
        append=yes

- name: Restart docker 
  service:
    name: docker
    state: restarted