  - name: restart host
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    become: yes

  - name: Wait for shutdown
    pause: seconds=15

  - name: Capture hostname
    debug: var=ansible_host
    register: reboot_host

  - name: wait for host
    wait_for:
      delay: 1
      host: "{{ reboot_host.ansible_host }}"
      port: 22
      state: started
      timeout: 360
    delegate_to: localhost

  - name: Wait for restart
    pause: seconds=15