- name: Add custom-rules
  uri:
    url: "{{ twistlock_console }}/api/v1/policies/runtime/custom-rules/{{ (item | basename).split('-')[0] }}"
    body: "{{ lookup('file','{{ item }}' ) }}"
    method: PUT
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    status_code: 200
  when: twistlock_version.split('.')[0] != "18"
  with_fileglob:
    - "custom-rules/*.json"

- name: Add custom compliance check
  uri:
    url: "{{ twistlock_console }}/api/v1/custom-compliance"
    body: "{{ lookup('file','{{ item }}' ) }}"
    method: PUT
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    status_code: 200
  when: twistlock_version.split('.')[0] != "18"
  with_fileglob:
    - "custom-compliance/*.json"
