- name: Restart docker
  service:
    name: docker
    state: restarted

- name: we need to wait for it all to start up...
  uri:
    url: "http://127.0.0.1:8081/api/v1/_ping"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1 