- name: Enable kubernetes-audit webhook in Console
  uri:
    url: "{{ twistlock_console }}/api/v1/policies/kubernetes-audit"
    method: PUT
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    body: "{{ lookup('template','kube-audit/kube-audit-settings.json.j2') }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    status_code: 200
  when: twistlock_version.split('.')[0] != "18"

- name: Copy k8s audit sink yaml
  template:
    src: kube-audit/kube-audit.yml.j2
    dest: /opt/kube-audit.yml

- name: Configure k8s audit sink
  shell: kubectl apply -f /opt/kube-audit.yml

- name: Recreate the Console pod to ensure webhook is active
  shell: kubectl delete $(kubectl get pods -n twistlock -l name=twistlock-console -o name) -n twistlock

- name: we need to wait for it all to start up...
  uri:
    url: "{{ twistlock_console }}/api/v1/_ping"
    status_code: 200
    validate_certs: false
  register: result
  until: result is succeeded
  retries: 20
  delay: 10 
  delegate_to: localhost