- name: Build Twistlock Kubeconfig Test
  shell: cat /root/.kube/config | sed ':a;N;$!ba;s/\n/\\n/g'
  register: console_kubeconfig
  delegate_to: "{{ groups['k8s-master'][0] }}"

- name: Add Kubeconfig credential
  uri:
    url: "{{ twistlock_console }}/api/v1/credentials"
    method: POST
    user: "{{ console_user }}"
    password: "{{ console_password }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: no
    body: '{"secret":{"plain":"{{ console_kubeconfig.stdout }}"},"serviceAccount":{},"apiToken":{},"type":"kubeconfig","_id":"Kubeconfig"}'
