- name: Construct DNS list
  set_fact: additional_dns_predicates='{{ additional_dns_predicates |default([]) + [item]  }}'
  with_items:
    - console
    - jenkins
    - splunk
    - k8s
    - sockshop
    - defender
    - gogs
    - mail
    - harbor

- debug: var=additional_dns_predicates

- name: create a place for portal
  file: dest="/opt/portal" owner=root group=root mode=0755 state=directory

- name: create a place for portal HTML
  file: dest="/opt/portal/public-html" owner=root group=root mode=0755 state=directory

- name: Copy default.html
  template:
    src: portal/default.html.j2
    dest: /opt/portal/public-html/index.html

- name: Copy Dockerfile for portal
  copy:
    src: portal-httpd/Dockerfile
    dest: /opt/portal/Dockerfile

# building with docker commands instead of
# ansible native tasks because
# Twistlock unix socket seems
# to break ansible
- name: Build portal container
  command: "docker build /opt/portal -t registry.infra.svc.cluster.local:5000/infra/portal_httpd"

- name: Push portal container to registry
  command: "docker push registry.infra.svc.cluster.local:5000/infra/portal_httpd"

- name: Copy portal yaml
  template:
    src: portal/portal.yml.j2
    dest: /opt/portal.yml

- name: Create portal deployment
  shell: kubectl apply -f /opt/portal.yml
