
    # This is the handler to restart the operating system
  - name: restart host
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
    notify: Wait for shutdown
    become: yes

  - name: Wait for shutdown
    pause: seconds=15
    notify: wait for host

  - name: wait for host
    wait_for:
      delay: 1
      host: "{{ ansible_host }}"
      port: 22
      state: started
      timeout: 360
    delegate_to: localhost