name: Source Code Scan

on: [push,pull_request]

jobs:
  scan-source-code:
    name: Scan Source Code
    runs-on: ubuntu-latest
    env: 
      PROJECT_KEY: factory # Set the desired project to run the cli scanning with
    
    steps:
    # checks-out your repository under $GitHub_WORKSPACE, so your workflow can access it.
    - name: Checkout
      uses: actions/checkout@v2
  
      
    - name: Run Orca FS Scan
      uses: orcasecurity/shiftleft-fs-action@v1
      with:
        api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
        project_key: default
        path: test
        format: sarif
        output: results/
        console_output: table
        show_annotations: false
    - uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results/file_system.sarif
